[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  timeout = 1800 # 30 minutos
  ignore = "git diff --quiet HEAD^ HEAD ./"
  
[build.environment]
  NODE_VERSION = "18.19.0"
  NODE_OPTIONS = "--max-old-space-size=4096"
  CI = "false"
  NPM_FLAGS = "--no-audit --no-fund --prefer-offline"

[dev]
  command = "npm run dev"
  port = 8889
  targetPort = 5173
  publish = "dist"
  autoLaunch = true
  framework = "vite"
  functionsPort = 8889

# Redirección para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirección para API/funciones
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
